LEGEND_FORMS: tuple[str, ...] = (
    "легенда",
    "легенды",
    "легенде",
    "легенду",
    "легендой",
    "легендам",
    "легендами",
    "легендах",
    "legend",
    "legends",
)
MYTH_FORMS: tuple[str, ...] = (
    "миф",
    "мифа",
    "мифу",
    "мифом",
    "мифе",
    "мифы",
    "мифов",
    "мифам",
    "мифами",
    "мифах",
    "myth",
    "myths",
)
STRONG_CLAIM_MARKERS: tuple[str, ...] = (
    "по преданию",
    "согласно преданию",
    "предание",
    "по легенде",
    "согласно легенде",
    *LEGEND_FORMS,
    "согласно сказанию",
    "сказание",
    *MYTH_FORMS,
    "якобы",
    "будто бы",
    "по слухам",
    "legend has it",
    "according to legend",
    "according to tradition",
    "tradition has it",
    "allegedly",
    "supposedly",
    "it is said",
    "is said to",
    "apocryphal",
)
WEAK_CLAIM_MARKERS: tuple[str, ...] = (
    "согласно летописи",
    "по летописи",
    "летопись",
    "согласно хронике",
    "хроника",
    "согласно житию",
    "считается",
    "принято считать",
    "утверждается",
    "утверждают",
    "по мнению",
    "по одной из версий",
    "по другой версии",
    "версия",
    "по некоторым данным",
    "по некоторым сведениям",
    "говорят",
    "бытует",
    "распространено мнение",
    "распространённое утверждение",
    "многие источники",
    "в некоторых источниках",
    "в ряде источников",
    "источники указывают",
    "указывается",
    "делается вывод",
    "according to",
    "reportedly",
    "many sources",
    "some sources",
    "it is claimed",
    "it is believed",
)
CLAIM_MARKERS: tuple[str, ...] = STRONG_CLAIM_MARKERS + WEAK_CLAIM_MARKERS
REBUTTAL_OPENERS: tuple[str, ...] = (
    "однако",
    "на самом деле",
    "в действительности",
    "however",
    "in fact",
    "actually",
)
REBUTTAL_MARKERS: tuple[str, ...] = (
    *REBUTTAL_OPENERS,
    "в реальности",
    "опроверг",
    "не подтверждается",
    "ошибочно",
    "неверно",
    "заблуждение",
    "in reality",
    "refuted",
    "disproved",
    "erroneous",
    "no evidence",
)
STANCE_MARKER_EXACT_WORDS: frozenset[str] = frozenset({*LEGEND_FORMS, *MYTH_FORMS})
STANCE_CONTEXT_SENTENCES = 1
